### ISSUE TITLE
Built-in speaker output only or other output options?

### ISSUE THREAD

**Issue by m-r-m-s** [movetones/Gravitone_ArduinoLibrary#2]
Hi Gravitone folx,
I just came across your project and congrats. It looks and sounds fantastic! Are there other output options planned or available than the built in speaker?

**Comment by ruffner** [comment]
Hi,

Thanks! 

Audio output (and input) is available over USB thanks to the Teensy Audio library. Check out the MIDIWand example at https://github.com/movetones/Gravitone_ArduinoLibrary/tree/v1.2/examples/MIDIWand for a simple MIDI note sender.  This example uses a minimal effects chain. To create a more complex array of effects, check out the Teensy audio system design tool https://www.pjrc.com/teensy/gui/. You can string together some pretty advanced DSP functionality and use the Gravitone's motion and buttons to control effect parameters.

**Comment by m-r-m-s** [comment]
Great - thank you for letting me know.

**Comment by ruffner** [comment]
@m-r-m-s you can get a Gravitone kit here https://movetones-store.myshopify.com/. Use code GTONE at checkout to get 30% off.

**Comment by ruffner** [comment]
@m-r-m-s the library now has support for  USB audio output by default.
